### ISSUE TITLE
Hard to understand error "no provider exists with the given name"

### ISSUE THREAD

**Issue by mwarkentin** [bridgecrewio/yor#107]
I was trying to run `yor` for testing on one of our dev applications in our terraform monorepo. When I ran it I got the following error which doesn't really indicate what I can do to fix it. Eg. which provider is it having issues with, etc.

```
❯ yor tag --directory envs/cetus/receipts
2021/05/27 14:00:16 [ERROR] failed to install provider for directory envs/cetus/receipts because of errors no provider exists with the given name
```

**Comment by ismailyenigul** [comment]
Do you have any terraform code in envs/cetus/receipts base directory (not asking for sub directories) ?

**Comment by mwarkentin** [comment]
@ismailyenigul Yes, looks like it's mainly resources defined inside of modules which it looks like `yor` might not support at this point?

Here's an example of the contents of our providers definitions:

![](https://s3.amazonaws.com/mwarkentin-snaps/providers.tf__keller_2021-05-27_14-30-40.jpg)

We're using terraform 0.12 and some community providers installed locally, I would suspect this could be related?

**Comment by nimrodkor** [comment]
Thanks for reporting & for the code example @mwarkentin !

Fix will be released soon, let me know if it didn't solve your issue

**Comment by mwarkentin** [comment]
@nimrodkor after upgrading through brew it shows that the warning (used to be error) is related to one of the community providers we're installing locally:

```
2021/05/28 15:31:53 [WARNING] failed to install provider "sentry" for directory envs/cetus/receipts because of errors no provider exists with the given name
```

Still not seeing any tags added to resources (although not sure how / if this should work with resources defined in modules).

**Comment by nimrodkor** [comment]
@mwarkentin Hmmm... Yor supports the 3 cloud provider resources today, i.e. AWS (`aws_*`), GCP (`google_*`) and Azure (`azurerm_*`) Do you have resources from these providers in your directory?

**Comment by mwarkentin** [comment]
@nimrodkor sorry, meant to respond to this and it fell off my radar.

Within this terraform project we have a bunch of aws resources, however they're included within modules rather than defined directly. It's not clear to me if tagging resources within modules are supported or not. Some of the resources within modules that we have are:

* `aws_rds_instance`
* `aws_s3_bucket`
* `aws_s3_bucket_policy`
