### ISSUE TITLE
yor On Linux & Windows?

### ISSUE THREAD

**Issue by Relativity11** [bridgecrewio/yor#127]
Is there any installers for Linux and Windows?

**Comment by nimrodkor** [comment]
Hi @Relativity11 !
We do have executables for linux and windows for every release (https://github.com/bridgecrewio/yor/releases/latest).
However, we don't yet package them in any installers. We're open for contributions of that if you're interested!

**Comment by nimrodkor** [comment]
Please see the updated readme :)
https://github.com/bridgecrewio/yor#installation
