### ISSUE TITLE
Can't run yor on MacOS

### ISSUE THREAD

**Issue by blackdenc** [bridgecrewio/yor#135]
MacOS Version 10.14.6
Terraform v0.14.6
Go version go1.16.4 darwin/amd64

All yor commands fail to run, including `yor --version`. This is the same when installed through homebrew and when build from source.

Expected output:
```
yor version 0.1.59
```

Actual output:
```
./yor --version
runtime: netpoll: break fd ready for -2
fatal error: runtime: netpoll: break fd ready for something unexpected
runtime stack:
runtime.throw(0x5df86e7, 0x39)
	/usr/local/Cellar/go/1.16.4/libexec/src/runtime/panic.go:1117 +0x72
runtime.netpoll(0x16ea5e, 0x14bdedda9e06)
	/usr/local/Cellar/go/1.16.4/libexec/src/runtime/netpoll_kqueue.go:147 +0x33e
runtime.findrunnable(0xc000073800, 0x0)
	/usr/local/Cellar/go/1.16.4/libexec/src/runtime/proc.go:2923 +0x3ee
runtime.schedule()
	/usr/local/Cellar/go/1.16.4/libexec/src/runtime/proc.go:3169 +0x2d7
runtime.park_m(0xc000001b00)
	/usr/local/Cellar/go/1.16.4/libexec/src/runtime/proc.go:3318 +0x9d
runtime.mcall(0x80000)
	/usr/local/Cellar/go/1.16.4/libexec/src/runtime/asm_amd64.s:327 +0x5b
goroutine 1 [runnable, locked to thread]:
golang.org/x/text/internal/language.getLangID(0xc0005acb18, 0x2, 0x20, 0x80, 0x5bbf260, 0x5468617)
	/Users/blackdenc/go/pkg/mod/golang.org/x/text@v0.3.3/internal/language/lookup.go:39 +0xbb
golang.org/x/text/internal/language.parseTag(0xc00051cbd8, 0x0, 0x0, 0x0, 0x5dab424)
	/Users/blackdenc/go/pkg/mod/golang.org/x/text@v0.3.3/internal/language/parse.go:294 +0x6d
golang.org/x/text/internal/language.parse(0xc00051cbd8, 0x5dab424, 0xe, 0x0, 0x0, 0x0, 0x6169636e656c, 0x0)
	/Users/blackdenc/go/pkg/mod/golang.org/x/text@v0.3.3/internal/language/parse.go:265 +0x236
golang.org/x/text/internal/language.Parse(0x5dab424, 0xe, 0x0, 0x0, 0x0, 0x1, 0xc00004e220)
	/Users/blackdenc/go/pkg/mod/golang.org/x/text@v0.3.3/internal/language/parse.go:250 +0x215
golang.org/x/text/internal/language.MustParse(...)
	/Users/blackdenc/go/pkg/mod/golang.org/x/text@v0.3.3/internal/language/tags.go:10
golang.org/x/text/internal/language/compact.init.0()
	/Users/blackdenc/go/pkg/mod/golang.org/x/text@v0.3.3/internal/language/compact/compact.go:59 +0x13e
goroutine 19 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00013de50)
	/Users/blackdenc/go/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:154 +0xcd
created by go.opencensus.io/stats/view.init.0
	/Users/blackdenc/go/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:32 +0x57
```

**Comment by nimrodkor** [comment]
Hi @blackdenc !

I can't really reproduce this, trying to get more context.
1. Does this happen from every directory you run it?
2. `brew` basically builds yor from source - do you mind trying out the pre-build package found [here](https://github.com/bridgecrewio/yor/releases/latest)?
Latest mac version - https://github.com/bridgecrewio/yor/releases/download/0.1.60/yor-0.1.60-darwin-amd64.tar.gz

**Comment by blackdenc** [comment]
So when installed with brew or built on my machine, it throws that error in any directory for any command. When I downloaded the pre-built package and extracted it, yor worked as expected. Might be an issue with my machine, but I can reproduce it anytime I build or install using homebrew on my device.

**Comment by nimrodkor** [comment]
Thanks. I'm glad the prebuilt package worked. 
There are 2 options now:
1. Update the brew formula to use the packaged version.
2. Get to the root of it.

We'll pursue both, keeping this issue open for now

**Comment by blackdenc** [comment]
Great, thanks. Right now, I can use the packaged version, but this is going to block using yor in a pre-commit hook because it has to build the environment before running the hook

**Comment by nimrodkor** [comment]
It seems to be something in your existing go setup. I've tracked it down to https://github.com/golang/go/issues/37726
Does this help? Maybe a different version of yor is the way to go?

**Comment by blackdenc** [comment]
It doesn't really help here because there's no clear way to fix it from my end. If I change the log level to debug and re-install yor from homebrew, it does look like that's the issue. If I were going to try a different version of yor, which one would be a good candidate?

```
 ❯ LOG_LEVEL=DEBUG
❯ yor version
runtime: netpoll: break fd ready for -2
fatal error: runtime: netpoll: break fd ready for something unexpected

runtime stack:
runtime.throw(0x5df86bb, 0x39)
	runtime/panic.go:1117 +0x72
runtime.netpoll(0x267497, 0x393a54e78ca)
	runtime/netpoll_kqueue.go:147 +0x33e
runtime.findrunnable(0xc000071000, 0x0)
	runtime/proc.go:2923 +0x3ee
runtime.schedule()
	runtime/proc.go:3169 +0x2d7
runtime.park_m(0xc000001200)
	runtime/proc.go:3318 +0x9d
runtime.mcall(0x80000)
	runtime/asm_amd64.s:327 +0x5b

goroutine 1 [runnable, locked to thread]:
os.newFile(0x5, 0x5d7a853, 0x6, 0x3, 0x0)
	os/file_unix.go:127 +0x89
os.NewFile(0x5, 0x5d7a853, 0x6, 0xc0007b6008)
	os/file_unix.go:106 +0x65
github.com/hashicorp/terraform/helper/wrappedstreams.initPlatform()
	github.com/hashicorp/terraform@v0.14.0/helper/wrappedstreams/streams_other.go:13 +0xbc
github.com/hashicorp/terraform/helper/wrappedstreams.init.0()
	github.com/hashicorp/terraform@v0.14.0/helper/wrappedstreams/streams.go:51 +0x25

goroutine 19 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000145ea0)
	go.opencensus.io@v0.22.0/stats/view/worker.go:154 +0xcd
created by go.opencensus.io/stats/view.init.0
	go.opencensus.io@v0.22.0/stats/view/worker.go:32 +0x57
```

**Comment by nimrodkor** [comment]
Hey @blackdenc, we are still trying to figure this one out. in the meanwhile - you can try to use the [dockerized version](https://github.com/bridgecrewio/yor#installation) of yor.

**Comment by nimrodkor** [comment]
Hey again @blackdenc !

We've modified the brew formula - can you try and install it via Homebrew and let us know if it worked out for you?

**Comment by blackdenc** [comment]
Success! I am able to install yor from homebrew and ran a list-tags command without errors!
