### ISSUE TITLE
Can .yor_plugins be at the users home directory vs. CWD?

### ISSUE THREAD

**Issue by brettcurtis** [bridgecrewio/yor#139]
I know I can easily add .yor_plugins to .gitignore however it seems unnecessary to copy the plugins all over the place. Minimally a single .yor_plugin for each repo would be nice, or just get it out of the repo all together and move to ~/.yor_plugins.

Thanks!

**Comment by schosterbarak** [comment]
this is a good idea. will talk with @nimrodkor once he's back from holiday :)

**Comment by nimrodkor** [comment]
I like this!
