### ISSUE TITLE
github-actions[bot] not valid for tag regex

### ISSUE THREAD

**Issue by blackdenc** [bridgecrewio/yor#141]
When run as a github action, yor produces the following tags block on an `aws_iam_policy` resource
```
resource "aws_iam_policy" "test-policy" {
  <Resource configuration>

  tags = {
    git_last_modified_by = "41898282+github-actions[bot]@users.noreply.github.com"
    git_modifiers        = "41898282+github-actions[bot]/blackdenc"
  }
}
```
When `terraform apply` is run on this resource, the following error is thrown:
```
Error: error updating tags for IAM Policy (<ARN>): error tagging resource (<ARN>): ValidationError: 2 validation errors detected: Value '41898282+github-actions[bot]@users.noreply.github.com' at 'tags.1.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{Z}\p{N}_.:/=+\-@]*; Value '41898282+github-actions[bot]/blackdenc' at 'tags.2.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{Z}\p{N}_.:/=+\-@]*
        status code: 400, request id: 08e80e1e-8dd1-4bb3-b013-4df5b5ec576c

  on <FILENAME> line 53, in resource "aws_iam_policy" "test-policy":
  53: resource "aws_iam_policy" "test-policy" {
```

`41898282+github-actions[bot]` Was the user that added the tags on the initial yor workflow run on this resource. I removed the bot username from the tag and re-ran `terraform apply` and the resource deploy ed without issues.

Can we change the name of the the github actions user that makes the change in order to match regex?

**Comment by blackdenc** [comment]
Update: I just removed `[bot]` from the tag and applied it successfully, so I think that the regex doesn't allow for `[` and `]` characters.

**Comment by nimrodkor** [comment]
Thanks for reporting @blackdenc !
I believe there is no value in adding GHA bot as a modifier, let me see if I can skip it altogether
