### ISSUE TITLE
Support git tags when --directory != git root

### ISSUE THREAD

**Issue by mwarkentin** [bridgecrewio/yor#142]
We have a github repo which looks like this:

```
root/
  .git/
  accounts/
    acc1/
    acc2/
    ...
  envs/
    env1/
      app1/
      app2/
      ...
    env2/
      app1/
      app2/
      ...
    ...
```

I would like to be able to run `yor tag --directory envs/env1/app1` from the root directory. When I do so currently, `yor` doesn't seem to set the git tags. I assume this is because the `.git` repo is in the root and not the directory I've configured.

A few options that would resolve for me:

* Pick up `git` metadata from the directory where `yor` is run, not from `--directory` setting
* Search up in the tree from `--directory` if a `.git` dir is not found
* Add a `--git-dir` option that lets me configure it directly

**Comment by nimrodkor** [comment]
Thanks for reporting @mwarkentin !
Found the issue, should be resolved and released soon (PR is open)
