### ISSUE TITLE
Repo does not have .pre-commit-hooks.yaml

### ISSUE THREAD

**Issue by gregwhorley** [bridgecrewio/yor#148]
I added yor to one of my repos' `.pre-commit-config.yaml` files with settings taken from the readme:

```yaml
- repo: https://github.com/bridgecrewio/yor
    rev: 5d56b61447940e9928426e4df6b577f28000cd6d  # frozen: v0.1.65
    hooks:
      - id: yor
        name: yor
        entry: yor tag -d
        args: ["terraform"]
        language: golang
        types: [terraform]
        pass_filenames: false
```

Then added the config file to a git branch so that I could execute `pre-commit run` and try it out, but an exception was thrown during initialization:

```
$ pre-commit run
[INFO] Initializing environment for https://github.com/bridgecrewio/yor.
An error has occurred: InvalidManifestError:
=====> /Users/gwhorley/.cache/pre-commit/repoxhvlei6s/.pre-commit-hooks.yaml does not exist
Check the log at /Users/gwhorley/.cache/pre-commit/pre-commit.log
```

The log only provided a stacktrace along with the error shown above. The contents of that cached directory contains the cloned repo with no .pre-commit-hooks.yaml. What am I missing?

**Comment by nimrodkor** [comment]
@JamesWoolfenden mind taking a look at this?
