### ISSUE TITLE
Module tags for Google (they use the word "labels")

### ISSUE THREAD

**Issue by brettcurtis** [bridgecrewio/yor#158]
**Describe the bug**
Looks like yor will not populate labels for GCP modules with "labels" for example:
```
module "project" {
  source = "git@github.com:my-org/terraform-google-project?ref=v2.1.3"

  prefix            = var.app_abbrev
  system            = var.system
  env               = var.env
  random_project_id = var.random_project_id
  labels = {
  }
}

```

Changing labels to tags populates fine. For consistency I'd like to see tags = labels with modules in Google.

Thanks!

**Comment by nimrodkor** [comment]
Was fixed in #164
