### ISSUE TITLE
Need the ability to skip files and/or resources

### ISSUE THREAD

**Issue by blackdenc** [bridgecrewio/yor#166]
**Is your feature request related to a problem? Please describe.**
I need a way to skip tagging individual files/resources instead of only directories. 

**Describe the solution you'd like**
Add a new parameter or modify existing `skip-dirs` parameter to accept file names or terraform resource IDs.

**Comment by nimrodkor** [comment]
This is great, we're open to contributions here!

**Comment by nimrodkor** [comment]
#183 Supports skipping resource types, which partially resolves this
