### ISSUE TITLE
Brew tap/install from fresh doesn't work

### ISSUE THREAD

**Issue by richardj-bsquare** [bridgecrewio/yor#168]
**Describe the bug**
The first time ever installing doesn't seem to work for me. The error is not particularly helpful.
Are there some missing dependencies (compilers, Xcode, etc.)?

**To Reproduce**

$ brew tap bridgecrewio/tap
brew install bridgecrewio/tap/yor
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from 3e52e8b48 to 89b861915.
Updated 4 taps (homebrew/cask-versions, homebrew/core, homebrew/cask and homebrew/cask-fonts).
==> New Formulae
umple
==> Updated Formulae
Updated 84 formulae.
==> Updated Casks
Updated 77 casks.
==> Deleted Casks
beautune                                                                blue-jeans-browser-plugin                                               caramba-switcher

==> Tapping bridgecrewio/tap
Cloning into '/usr/local/Homebrew/Library/Taps/bridgecrewio/homebrew-tap'...
remote: Enumerating objects: 325, done.
remote: Counting objects: 100% (325/325), done.
remote: Compressing objects: 100% (214/214), done.
remote: Total 325 (delta 105), reused 20 (delta 4), pack-reused 0
Receiving objects: 100% (325/325), 31.70 KiB | 3.96 MiB/s, done.
Resolving deltas: 100% (105/105), done.
Tapped 1 formula (12 files, 45KB).
==> Installing yor from bridgecrewio/tap
==> Cloning https://github.com/bridgecrewio/yor.git
Cloning into '/Users/richardj/Library/Caches/Homebrew/yor--git'...
==> Checking out tag 0.1.85
HEAD is now at 4b31cf4 When adding tags to templates, validate modified template is acceptable (#167)
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - yor

**Expected behaviour**
Yor installed

**Desktop (please complete the following information):**
 - OS: Big Sur 11.4
 - Yor Version (see above)

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by rotemavni** [comment]
Hi @richardj-bsquare 
Thanks for reporting this issue, it is now fixed.
Can you please confirm it works for you?

**Comment by richardj-bsquare** [comment]
Yor, it's fixed.
