### ISSUE TITLE
[Inquiry] Can Yor help to create and adjust tags from resources already created?

### ISSUE THREAD

**Issue by Relativity11** [bridgecrewio/yor#172]
Title says it all:
Is yor only able to enforce tagging for incoming resources being created from IaC?

**Comment by nimrodkor** [comment]
Hi @Relativity11 !

If I understand you correctly, you are referencing resources which already exist in your cloud account, and you want to add tags to them.
In that case - no, Yor doesn't support that as of today. I'd love to hear more of your use case.

CC: @schosterbarak @metahertz
