### ISSUE TITLE
Auto network tags

### ISSUE THREAD

**Issue by Zest-nikunj** [bridgecrewio/yor#177]
**Is your feature request related to a problem? Please describe.**
Today, I can use yor to add labels to my resources, however I am looking for ability to be able to add Network Tags (GCP) to my resources as well.

**Describe the solution you'd like**
Ability to add Network tags via yor

**Comment by Zest-nikunj** [comment]
@nimrodkor Would appreciate your inputs here.

**Comment by nimrodkor** [comment]
Interesting use-case @Zest-nikunj ! Sorry for the late reply.

Can you give me an example of a tag you would like to implement? I'm not as strong in GCP...

**Comment by Zest-nikunj** [comment]
@nimrodkor Apologies, did not see this earlier! Since we usually work with GCP, hence the usecase is related to it,
GCP has networking option, where the communication between two or more entities can happen based on "network tags". These network tags can be applied to various resources, like a GCE(VMs). Now, the firewall rules can as well can be created around these network tags, say I have a network tag "yor-npe" and there is a rule that says, all resources with "yor-npe" tag can communicate with "yor-perf" tags for port 443. In this case, as soon as a resource is created, the communication can be established between these entities without any changes to the system. The best part is, it is all recorded in code. 
Terraform has a way to facilitate that e.g. https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#tags
For a firewall e.g.
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_firewall#example-usage---firewall-with-target-tags
My proposal is, yor can provide an option where along with resource labels, we have an ability to append logs to the code as well.

**Comment by nimrodkor** [comment]
@Zest-nikunj Apologies as well, it was holiday season here is Israel as well :)

This sounds really, really interesting. We're open to contributions on this. My take on it:
I think this should be a tag group (just like the [git tag group](/bridgecrewio/yor/blob/main/src/common/tagging/gittag/git_tag_group.go) or the [code2cloud tag group](/bridgecrewio/yor/blob/main/src/common/tagging/simple/tag_group.go). However - the tag key + value are not something I think is conventional (such as git tags). We can always support adding those tags via the [external tag group yaml](/bridgecrewio/yor/blob/main/docs/3.Custom%20Taggers/Custom_tagger_YAML.md) file.

What do you think?
