### ISSUE TITLE
Guidance/Question on workflow if using Azure DevOps Repos

### ISSUE THREAD

**Issue by hramos05** [bridgecrewio/yor#186]
On the announcement blog: https://bridgecrew.io/blog/announcing-yor-open-source-iac-tag-trace-cloud-resources/, if using GitHub, we can leverage the action stefanzweifel/git-auto-commit-action@v4. Is there something similar or guidance for Azure DevOps?

**Comment by nimrodkor** [comment]
Hi @hramos05 !

That action is just used for making the commit. You can implement the commit in any way you see fit. It's just easier with GHA

**Comment by hramos05** [comment]
Will find a solution, thanks!
