### ISSUE TITLE
Windows releases to .zip

### ISSUE THREAD

**Issue by hramos05** [bridgecrewio/yor#193]
**Describe the bug**
Recent releases for windows started to have "tar.gz", can this be reverted back to ".zip"?

There was also a recent change to use _ instead of -

Old artifact have the following convention:
yor-0.1.88-windows-amd64.zip

Recent ones:
yor_0.1.101_windows_amd64.tar.gz

**Comment by paulmowat** [comment]
I'll fix this one over next few days.
