### ISSUE TITLE
Custom tag group directory filter - support wildcards

### ISSUE THREAD

**Issue by nimrodkor** [bridgecrewio/yor#213]
**Is your feature request related to a problem? Please describe.**
When using the custom tag group with directory filter, today it supports exact prefix - i.e. `path/to/dir-tree`. I'd like to be able to tag with a specific tag all the directories which match a specific regex / joker. Example - tag everyhing that's in a directory named `infra/networkign` as `Component: Networking`.

**Describe the solution you'd like**
Extending the existing `HasPrefix` to support regex correctly.
https://github.com/bridgecrewio/yor/blob/389382c952147a12c8e0f825334b6c1096837996/src/common/tagging/external/tag_group.go#L92

**Describe alternatives you've considered**
Writing out all the possibilities is time consuming and not scalable.

**Comment by AsianCat54x** [comment]
Thanks ;)
