### ISSUE TITLE
Support for non-recursive tagging

### ISSUE THREAD

**Issue by skyzyx** [bridgecrewio/yor#249]
**Is your feature request related to a problem? Please describe.**
I'm toying with adding this to our Terraform module builds. The concept is interesting, but it chokes when I just point it to `.` because there are subdirectories that it attempts to scan (e.g., `.vscode/settings.json`, `./tests`, `./examples`). In order to keep the tagging at only that level, I have to `ls` to look up the directory names, and manually add them to the `--skip-dirs` parameter.

**Describe the solution you'd like**
A non-recursive option which limits the searching to only the current directory.

**Describe alternatives you've considered**
I've tried `--skip-dirs *`, `--skip-dirs "*"`, and `--skip-dirs "*,.*"` to no avail.

**Additional context**
Using latest Terraform (1.0.10) and `yor` downloaded from Homebrew _today_.

**Comment by nimrodkor** [comment]
Hey @skyzyx !

I like this idea, we'd love a contribution if you're up for it!
Changes should be around:
Creating the flag - https://github.com/bridgecrewio/yor/blob/3a89e3de92368fdab151252bef670c6597c42a85/src/common/clioptions/cli.go#L17
Saving the flag to the runner instance - https://github.com/bridgecrewio/yor/blob/3a89e3de92368fdab151252bef670c6597c42a85/src/common/runner/runner.go#L43
And then avoiding the recursive walking of the directory tree here:
https://github.com/bridgecrewio/yor/blob/3a89e3de92368fdab151252bef670c6597c42a85/src/common/runner/runner.go#L114
