### ISSUE TITLE
skip_dirs doesn't function according to docs

### ISSUE THREAD

**Issue by BorisO** [bridgecrewio/yor#251]
**Describe the bug**
According to the README:
> yor tag -d path/to/files --skip-dirs path/to/files/skip,path/to/files/another/skip2
> Run yor on the directory path/to/files, skipping path/to/files/skip/ and path/to/files/another/skip2/

In reality the full path of the files should not be included in `skip_dirs` for it to work correctly.

**To Reproduce**
`yor tag -d apps --skip-dirs buildkite` works as intended.
`yor tag -d apps --skip-dirs apps/buildkite` tags all resources in `apps/buildkite`

**Expected behavior**
Based on the documentation I would expect `skip_dirs` to work opposite of how it is actually working.

**Desktop (please complete the following information):**
 - OS: `macOS Catalina 10.15.2`
 - Yor Version: `0.1.128`

**Comment by nimrodkor** [comment]
Thanks for reporting!
This should work now, and in the upcoming release (released within the next few minutes) based on #255 . If you run into this again - let us know!
