### ISSUE TITLE
[Question] Does yor support a --dry-run option

### ISSUE THREAD

**Issue by hartzell** [bridgecrewio/yor#254]
We avoid automation that changes the source tree without human feedback but this seems to be the model that yor currently uses (e.g. the GitHub action that adds tags to all the things and then commits them to the branch).

In our workflow (we do this with `terraform fmt` and `black` for python) we expect the branch as it is committed/pushed by the user to be correct and we have tests that run to confirm it is so (e.g., `pytest-black` or a script that runs `terraform fmt -check`).

I'd like to do something similar with `yor`; make it the responsibility of the dev to run `yor` and confirm that it did the right thing and write a test that calls `yor --check` or `yor --dry-run` and examine its exit code.

I can't see any `yor` cli flags that would make this possible.

Is it possible (am I missing something?)?

If not, how much work would it require (how big of a change is it?)?

**Comment by schosterbarak** [comment]
Hey @hartzell sounds like a great contribution opportunity :) 

if we want to have a dry-run option in Yor, we will need:
1. To add the CLI argument [here](https://github.com/bridgecrewio/yor/blob/main/src/common/clioptions/cli.go), for `TagOptions`, and implement tests [here](https://github.com/bridgecrewio/yor/blob/main/src/common/clioptions/cli_test.go)
2. Add the option to the runner's [Init](https://github.com/bridgecrewio/yor/blob/main/src/common/runner/runner.go#L43), and skip the actual file tagging [here](https://github.com/bridgecrewio/yor/blob/ac0988005f2c8b4547c8c0a152913728e2868c73/src/common/runner/runner.go#L189)

We will accept a pull request for this feature

**Comment by hartzell** [comment]
@schosterbarak -- Thanks for the pointers.

I dug into it a bit, and it's not as simple as you described.  The goal isn't to just skip tagging, but _to return an exit code based on whether any files would have been changed_.

In looking around the code, it looks like it rewrites _all_ of the files every time, presumably counting on a git commit to only include the ones that have actually changed.

There are two larger changes that would need to be made, I think.
- Each of the definitions of WriteFile (e.g. [this one for CloudFormation files](https://github.com/bridgecrewio/yor/blob/ac0988005f2c8b4547c8c0a152913728e2868c73/src/cloudformation/structure/cloudformation_parser.go#L225)) would need to be extended to compare the original and updated file and return a status if the file was actually updated; and
- The [worker function](https://github.com/bridgecrewio/yor/blob/ac0988005f2c8b4547c8c0a152913728e2868c73/src/common/runner/runner.go#L105) would need some way to communicate the "did I change any files" status back up to the upper layers.  It might also pass back a _list_ of the files that changed.

**Comment by tsmithv11** [comment]
Thank you @hi-artem!
