### ISSUE TITLE
yor Incorrectly updating git_modifiers tag

### ISSUE THREAD

**Issue by devbyaccident** [bridgecrewio/yor#261]
**Describe the bug**
`git_modifiers` tag is being updated with incorrect user name. 

My `.gitconfig` file is 
```
❯ cat ~/.gitconfig
[user]
        name = devbyaccident 
        email = github@charliebravo.33mail.com
```

But when yor adds the below tags to my resource.

```
   git_last_modified_by = "github@charliebravo.33mail.com"
   git_modifiers        = "github"
```

It looks like it's pulling the first part of my email address instead of my git username for the tag. Ideally, it should be pulling the username.

**To Reproduce**
1. Set .gitconfig
2. Run `yor tag -d .`
3. Observe `git_modifiers` tag

**Expected behavior**
`git_modifiers` should reflect the username value from .gitconfig, in this case, the expected results should mirror below:

```
   git_last_modified_by = "github@charliebravo.33mail.com"
   git_modifiers        = "devbyaccident"
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - yor version 0.1.84

**Additional context**
N/A

**Comment by nimrodkor** [comment]
Hey @devbyaccident !

Yes, you're correct. What you're referring to is something we've designed to help avoid terribly long modifiers list. If the modifier user contains an `@`, yor takes whatever comes before that, so for example: abcd@paloaltonetworks.com,efgh@paloaltonetworks.com,ijkl@paloaltonetworks.com,mnop@paloaltonetworks.com will turn into the short abcd,efgh,ijkl,mnop. However, in your use case, the prefix to the `@` is github, which is not helpful. 

I'm open to suggestions on this, but having the full emails of all the modifiers is not a scalable solution

**Comment by devbyaccident** [comment]
Right, I don't think that the list of email addresses in the tag would be useful, but a list of usernames might.

**Comment by nimrodkor** [comment]
Hey @devbyaccident !

I took another look at the git modifiers tag. It seems this is the struct we're getting, per line, from go-git:
```go
// Line values represent the contents and author of a line in BlamedResult values.
type Line struct {
	// Author is the email address of the last author that modified the line.
	Author string
	// Text is the original text of the line.
	Text string
	// Date is when the original text of the line was introduced
	Date time.Time
	// Hash is the commit hash that introduced the original line
	Hash plumbing.Hash
}
```

So sadly I cannot pull thie user.name field
