### ISSUE TITLE
Broken link for Demo on the README page

### ISSUE THREAD

**Issue by beckmani** [bridgecrewio/yor#264]
**Describe the bug**
Broken link on "What is Yor trace?" paragraph.

**To Reproduce**
1. Go to 'What is Yor trace?' paragraph on [README.md](https://github.com/bridgecrewio/yor#readme)
2. Click the demo link

**Expected behavior**
Redirect to demo page on yor.io

**Comment by schosterbarak** [comment]
Thanks! i just pushed a fix :)
