### ISSUE TITLE
Unable to tag modules using a generic git repository as source

### ISSUE THREAD

**Issue by ruortega** [bridgecrewio/yor#269]
**Describe the bug** 
Yor will not tag a module that is using a generic [git repository as source](https://www.terraform.io/language/modules/sources#generic-git-repository):

```
module "my_module" {
  source = "git::https://internal.repo.com/my-terraform-module.git?ref=vX.X.X"
  var1   = var.var1
  var2   = var.var2
  ...
}
```
Module not tagged when running `yor tag -d .` 
Output:

```
  __    __
  \ \  / /
   \ \/ /___  _  ____
    \  /  _ \| |/  __|
    | |  |_| |   /
    |_|\____/|__|v0.1.139
 Yor Findings Summary
 Scanned Resources:	  5
 New Resources Traced: 	  0
 Updated Resources:	  0
```

**Expected behavior** 
Module to be properly tagged

* Yor Version: 0.1.139

**Comment by rotemavni** [comment]
Hello @ruortega, thank you for raising this issue.

To reproduce I created this module
```
module "my_module" {
  source = "git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.19.2"
}
```

And ran `yor tag -d .` 
I could not detect a problem, and the module was tagged successfully: 

```
    "summary": {
        "scanned": 1,
        "newResources": 1,
        "updatedResources": 0
    }
```

In your example I see that you're trying to tag `internal.repo`. Since tagging a remote module requires `yor` to install the module, are you certain that the local machine has the required permissions to perform such an action on the internal repo?

**Comment by ruortega** [comment]
Hi @rotemavni, 

Thanks for the answer, but I'm not having any issues when using github.com as a source, those are working fine and being tagged accordingly, it is just when referencing repositories hosted on our git server.

**Comment by rotemavni** [comment]
@ruortega Got it, and do you have access to the git server from the machine running yor?

**Comment by ruortega** [comment]
Yes @rotemavni, no issues accessing the git server

**Comment by rotemavni** [comment]
@ruortega 
In order for us to be able to tag a remote module we need to an indication that the module is taggable, either by having the module block already tagged or by having a `tags` input in the module. 
Can you confirm that the module you are tagging does in fact contain a `tags` input?

**Comment by ruortega** [comment]
Thanks @rotemavni, changing the input name in the module to "tags" made the trick.
