### ISSUE TITLE
Add option for modules with a local path - tag_resoruces / tag_module

### ISSUE THREAD

**Issue by thecomalley** [bridgecrewio/yor#294]
I'd like to have an option to treat modules with a local path the same as modules with a remote path.

Ideally, a CLI flag could be passed to select if modules with a local path should be tagged using the current method (The underlying resources will be tagged separately) or with the method used for remote modules (tags will be added according to the module block metadata)

**Comment by JamesWoolfenden** [comment]
there is already a flag --tag-local-modules on tag?
