### ISSUE TITLE
Tagging adds a second set of tags to each file with syntax errors

### ISSUE THREAD

**Issue by cmartinsjr** [bridgecrewio/yor#306]
**Describe the bug**
When running the standard Yor tagging, we see a second set of tags added to the "merge" function in the tags section of the IaC files. We also see the variable in the value field after the second "Name" tag has two "$" instead of just one as is intended.

**To Reproduce**
1. Go to CMD.exe
2. Run cli command  'docker run --tty --volume C:\<path>\Repositories\Github\terragoat:\terraform bridgecrew/yor tag --directory \terraform'
3. The output in the IaC files tags look like this:
```  tags = merge({
    Name = "${local.resource_prefix.value}-ec2"
    }, {
    git_commit           = "N/A"
    git_file             = "terraform/aws/ec2.tf"
    git_last_modified_at = "2022-09-28 21:33:04"
    git_last_modified_by = "nimrodkor@gmail.com"
    git_modifiers        = "nimrodkor"
    git_org              = "cmartinsjr"
    git_repo             = "terragoat"
    yor_trace            = "347af3cd-4f70-4632-aca3-4d5e30ffc0b6"
    }, {
    Name                 = "$${local.resource_prefix.value}-ec2"
    git_commit           = "N/A"
    git_file             = "terraform/aws/ec2.tf"
    git_last_modified_at = "2022-09-28 21:33:04"
    git_last_modified_by = "nimrodkor@gmail.com"
    git_modifiers        = "nimrodkor"
    git_org              = "cmartinsjr"
    git_repo             = "terragoat"
    yor_trace            = "347af3cd-4f70-4632-aca3-4d5e30ffc0b6"
  })
}
```
**Expected behavior**
The expectation is that it should only have one set of tags applied and the "Name" value should only have a single "$" at the start of its variable.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Yor Version 0.1.151/latest version as of 9/28/22

**Comment by JamesWoolfenden** [comment]
ive see a duplicate set of tags added - it only seems to happen if you use docker under cmd. doesnt seem to happen under powershell.

**Comment by JamesWoolfenden** [comment]
@cmartinsjr  can you try this in powershell instead of cmd?

**Comment by richardgavel-ordinaryexperts** [comment]
I'm seeing duplicate tags added, and this is under WSL, Docker and I've tried a completely separate windows VM.

**Comment by richardgavel-ordinaryexperts** [comment]
I finally caught something that might have been my issue. Line endings. Under WSL/Dock/Linux VM, I had always been cloning on the host Windows machine and utilizing that, whether by sharing/mounting/copying. Once I cloned from within the WSL session, everything worked as expected. It even ran much faster (ran quite slow in all those sessions otherwise).
