### ISSUE TITLE
Skip tags and Tags are ignored

### ISSUE THREAD

**Issue by jasonckeating** [bridgecrewio/yor#313]
**Describe the bug**

When running yor against a directory of terraform resources all default tags are added.

Both of the following documented options are ignored:
```
OPTIONS:
   --tags value, -t value            run yor only with the specified tags (default: "yor_trace")
   --skip-tags value, -s value       run yor skipping the specified tags
```

When specifying `--tags`, all tags are added.
When specifying `--skip-tags`, all tags are added.

**To Reproduce**
1. Go to any directory of Terraform resources
2. Run cli command  `yor tag  -t yor_trace -d .`
3. See all tags are added to the resource
```
{
    git_commit           = "11111111111111"
    git_file             = "test.tf"
    git_last_modified_at = "2022-11-15 20:00:00"
    git_last_modified_by = "email@me.com"
    git_modifiers        = "john.smith"
    git_org              = "me"
    git_repo             = "test-resources"
    yor_trace            = "11111-1111-1111-11111-111111"
  }
```

**Expected behavior**
When specifying `--tags yor_trace` only the trace tag should be added as documented
```
{ 
     yor_trace            = "11111-1111-1111-11111-111111"
  }
```

**Screenshots**

**Desktop (please complete the following information):**
 - yor version 0.1.151

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by rotemavni** [comment]
@jasonckeating Can you please confirm that the `--tags` issue has been resolved?
