### ISSUE TITLE
Extra $ symbol in terraform (string interpolation) when using YAML groups

### ISSUE THREAD

**Issue by jsonarso** [bridgecrewio/yor#324]
**Describe the bug**
When trying to set a value for a tag that uses string interpolation syntax "${}" an extra $ symbol is added.

**To Reproduce**
1. Create a YAML file with a custom group
2. Add a new group with some tags as shown below
3. Run `yor tag --config-file path/to/config/file --skip-tags 'yor_trace,git*' -d .`
4. Even though the console output shows the correct value, when checking the file there is an extra $ symbol

**Expected behavior**
Value should be set as shown in the console output or there should be a way to add dynamic tags according to terraform variables

**Screenshots**
![image](https://user-images.githubusercontent.com/73246192/210467002-965ec1d8-7264-4c5e-8184-7f92e70b29a5.png)
![image](https://user-images.githubusercontent.com/73246192/210467138-08bdbaea-a26f-40e2-af16-7d46bdd48e86.png)
![image](https://user-images.githubusercontent.com/73246192/210467171-1f462390-4cb5-4049-83f4-519d4011ddc6.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Yor Version 0.1.72

**Additional context**
Tested on MACOS as well, same behavior

**Comment by JamesWoolfenden** [comment]
Hi @jason8496as have you got a sample tf file that this is repeatable on? As im not seeing it so far.

**Comment by jason8496as** [comment]
[Archive.zip](https://github.com/bridgecrewio/yor/files/10511883/Archive.zip)

I just uploaded both a sample tf file and also the tags.yml file I'm currently using.

I'm running `yor tag -d . --config-file tags.yml --skip-tags yor_trace,git*` against the root directory where that Terraform configuration is located.

**Comment by JamesWoolfenden** [comment]
Hi @jason8496as Ive tested this on a win 11 box with the latest code and a package version and failed to replicate it.
I have also test it on a M1 mac with the head and the version 0.1.161 and also failed to replicate it. 
Is there some other environmental factor? 
I know this was an issue in older version of the tool? maybe you still have one in your path? BTW the fail in the archive has the $${} version in it? Maybe its been committed to your VCS?

**Comment by jason8496as** [comment]
Weird, just reinstall YOR in my mac using Homebrew but still have the same behavior.

Yeah, I purposely sent you that tf file with the $${} so you can see how its being applied. I'm not aware about any other environmental factor at this moment.

Can you please share the example files you are using and also the command you are applying?

**Comment by JamesWoolfenden** [comment]
I just used your files and your stated command. odd i wish i could get top the bottom of it

**Comment by yogesh-ti** [comment]
I tried the terraform code provided by @jsonarso (after removing the tags block from the network.tf file) and it ends up adding the following
```
  tags = {
    environment = "$${var.environment}"
    source      = "terraform"
  }
```

**Comment by desenhar** [comment]
I am also experiencing this issue when attempting to use dynamic tags.
Using version '0.1.170'

**Comment by yogesh-ti** [comment]
@desenhar I have also noticed this issue happining on WSL where the line ending were CRLF. Got resolved by chnages to LF.

What is your system configuration and what is the line ending ?

**Comment by jfoster-hyland** [comment]
I also have ran into this issue running `yor version 0.1.174` on MacOs
