### ISSUE TITLE
No resources tagged for Serverless

### ISSUE THREAD

**Issue by andyshinn** [bridgecrewio/yor#339]
**Describe the bug**
A warning when trying to tag Serverless resources and no resources being tagged.

**To Reproduce**

Using following `serverless.yml`:

```
frameworkVersion: '3'
service: automations-base

provider:
  deploymentMethod: direct
  architecture: arm64
  endpointType: private
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}
  name: aws
  region: ${opt:region, 'us-east-1'}
  stackTags:
    app: automations
    deployed_by: ${env:DEPLOYED_BYTAG}
    domain: ${env:DOMAINTAG}
    env: ${env:ENVIRONMENT}
    managed_by: serverless
    service: ${self:service}
    stage: ${self:custom.tags.${opt:stage}, self:custom.stage}
    triggered_by: ${env:CIRCLE_USERNAME,'local'}
    version: ${env:VERSIONTAG}
  iam:
    deploymentRole: arn:aws:iam::${aws:accountId}:role/${env:EXECUTION_ROLE_NAME}


resources:
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/s3.yml)}
  - ${file(resources/event-bridge.yml)}

```

1. Set simple tags with `export YOR_SIMPLE_TAGS='{"managed_by":"serverless","app":"automations"}'`
2. Run cli command  `LOG_LEVEL=INFO yor tag --tag-groups simple -d services/base`
3. See output warning and no resources tagged

**Expected behavior**
Serverless resources should be tagged with `app` and `managed_by` keys.

**Screenshots**
```
❯ LOG_LEVEL=INFO yor tag --tag-groups simple -d services/base
2023/02/08 15:01:47 [INFO] Setting up to tag the directory services/base

2023/02/08 15:01:47 [INFO] Did not get an external config file
2023/02/08 15:01:47 [INFO] Tagging services/base/serverless.yml

2023/02/08 15:01:47 [INFO] Tagging services/base/resources/dynamodb.yml

2023/02/08 15:01:47 [INFO] Tagging services/base/resources/s3.yml

2023/02/08 15:01:47 [INFO] Tagging services/base/resources/event-bridge.yml

2023/02/08 15:01:47 [WARNING] There was an error processing the serverless template: json: cannot unmarshal array into Go struct field Template.functions of type map[string]serverless.Function
2023/02/08 15:01:47 [INFO] Failed to parse file services/base/serverless.yml with parser *structure.ServerlessParser
  __    __
  \ \  / /
   \ \/ /___  _  ____
    \  /  _ \| |/  __|
    | |  |_| |   /
    |_|\____/|__|v0.1.166
 Yor Findings Summary
 Scanned Resources:       0
 New Resources Traced:    0
 Updated Resources:       0
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Yor Version: `0.1.166`

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by nimrodkor** [comment]
Hi @andyshinn !

Looking at your file, it seems:
1. There is no `functions` block, which contains the functions (and that explains the error)
2. All `Resources` are managed in separate files. Since they look like CFN templates - perhaps tagging those resources directly would work better?

The actual bug you raised here is in a downstream parsing library, https://github.com/thepauleh/goserverless

**Comment by andyshinn** [comment]
OK. So, to clarify, yor doesn't actually look at the included resource file sin the `serverless.yml` file? Only resources defined directly in that file?
