### ISSUE TITLE
aws_s3_bucket_server_side_encryption_configuration doesn't support tags

### ISSUE THREAD

**Issue by andyshinn** [bridgecrewio/yor#340]
**Describe the bug**
The `aws_s3_bucket_server_side_encryption_configuration` resource is tagged but it doesn't support tags.

**To Reproduce**
2. Run cli command  '....'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Yor Version [e.g. 22]

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by JamesWoolfenden** [comment]
Im not seeing that behaviour with the latest and this resource
```
resource "aws_s3_bucket_server_side_encryption_configuration" "example" {
  bucket = aws_s3_bucket.mybucket.bucket

  rule {
    apply_server_side_encryption_by_default {
      kms_master_key_id = aws_kms_key.mykey.arn
      sse_algorithm     = "aws:kms"
    }
  }
}
```

can you specify the version and provide a sample that does cause the issue?

**Comment by andyshinn** [comment]
I am confused because I also cannot reproduce it now... If it comes up again I will try to make a more simple reproduction case.
