### ISSUE TITLE
create a yor.tf file with all the tags

### ISSUE THREAD

**Issue by mhristof** [bridgecrewio/yor#355]
**Is your feature request related to a problem? Please describe.**
When updating yor tags, i get a lot of spam in my merge requests because yor tags live in the resources.
This makes my code review harder as there are a lot of lines to mentally filter out.

**Describe the solution you'd like**
group all yor tags in a file, for example 

```tf
# yor.tf
aws_instance_foo_tags = {
"git_commit" = "blah"
}
```
and `merge` those tags in where the resource is, for example

```
# main.tf
resource "aws_instance" "foo" {
...
  tags = merge(local.aws_instance_foo_tags, {
    extra_tags = true
  })
```

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by jfechner-foxo** [comment]
Alternatively, if Yor could use the `default_tags` parameter on the AWS provider, it would cut down on the huge amount of changes Yor makes.
