### ISSUE TITLE
Yor could use a check mode (see PR#364)

### ISSUE THREAD

**Issue by hartzell** [bridgecrewio/yor#366]
A while back, in #254, I suggested that a dry-run mode would yor more useful, because I wanted to:

> write a test that calls yor --check or yor --dry-run and examine its exit code.

@hi-artem implemented the "don't actually change anything" side of the feature in #257, but it does not do anything useful with the exit status so we're left with parsing the CLI output.

I've submitted #364, which implements a `check` mode, which causes the output to be 0 if nothing changed and non-zero (via `log.Error` if anything changed (would have changed, if `--dry-mode`).

Feedback welcome.

**Comment by omryMen** [comment]
hey @hartzell,
the problem with changing the exit code is that you won't know if a real error occurred in the code which can be confusing.
if going for it, it makes sense to do only when running dry mode and not in regular run.
as for naming I would prefer calling it validation instead of check

**Comment by omryMen** [comment]
@hartzell what I meant is not to unite the flags. but when adding the new one you've suggested - make it turn on the dry mode as well, that way you will assure that this mode will have no side affects and only validate that there are no changes to be made

**Comment by hartzell** [comment]
@omryMen -- done.

**Comment by hartzell** [comment]
Closed by #364.
