### ISSUE TITLE
EBS Volumes Not Getting Tagged

### ISSUE THREAD

**Issue by yashg-ti** [bridgecrewio/yor#372]
**Describe the bug**
Terraform allows volume resources(ebs volume) to get defined and attached seperately, as well as within the instance's block. Taggings missing when volumes are defined internally(within the instance's block). The image shows ebs_block_storage property of an instance used to associate a volume to the instance.

**To Reproduce**
1. Create a terraform file with an ebs_block_device defined withn an ec2 instance's block, as shown in the image.
2. Run cli command  ' yor tag -d . --tag-groups code2cloud --parsers Terraform' to apply taggings
3. Find taggings missing in these ebs_blocks

**Expected behavior**
yor_tag within the tags{} property of the ebs_block_storage.

**Screenshots**
![islander's volume](https://github.com/bridgecrewio/yor/assets/133036599/e6a7b800-08af-432e-af21-e725e22d20e5)
the image shows missing tags in the ebs_block_devices after running the command.

**Desktop :**
 - OS: Ubunut 22.04
 - Yor Version: 0.1.150
 
**Additional context**
Apart from terraform, similar tagging issues exist for IaC tools like cloudformation too.

**Comment by nimrodkor** [comment]
Hey @yashg-ti !
This is an interesting use case, as what we are looking for here is actually tagging terraform blocks which are not resources - and that's something yor doesn't support. I see the use case though.
one possible way around this is to build a special block for aws_instance resource, which inherits from terraform_block, and change how it is tagged and how it is written to support this use case. Are you up for a contribution? This is not a small change...

**Comment by nimrodkor** [comment]
I do note that the other way to denote the addition of EBS volumes, via `aws_ebs_volume`, is supported OOTB...
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ebs_volume

**Comment by yashg-ti** [comment]
> Hey @yashg-ti !
> This is an interesting use case, as what we are looking for here is actually tagging terraform blocks which are not resources - and that's something yor doesn't support. I see the use case though.
> one possible way around this is to build a special block for aws_instance resource, which inherits from terraform_block, and change how it is tagged and how it is written to support this use case. Are you up for a contribution? This is not a small change...

Hey, thanks for the response! 
Sure, would be happy to contribute. Will raise a PR soon.

**Comment by elaygl** [comment]
@yashg-ti any update on that?


We have a similar use case. We want the EC2 to be tagged from the launch template.

**Comment by yashg-ti** [comment]
> @yashg-ti any update on that?
> 
> We have a similar use case. We want the EC2 to be tagged from the launch template.

Hey, actually we discarded the usage of tagging, hence didn't proceed further with fixing yor.
