### ISSUE TITLE
Invalid tags being added when there are comments in tag section of terraform file

### ISSUE THREAD

**Issue by sahilt-ti** [bridgecrewio/yor#376]
**Describe the bug**
If there is a comment anywhere within the tags block in a resource (except after the last tag), then invalid tags are being generated.

**To Reproduce**
1. Go to a working terraform project directory.
2. Use this template to reproduce:
```
provider "aws" {
  region = "us-east-1"
}

resource "aws_instance" "example" {
  ami           = "ami-09d56f8956ab235b3"
  instance_type = "t2.micro"
  tags = {
    "name" = "sahil" # this is name
    "env"  = "dev"
  }
}
```
3. Run cli command  `yor tag -d . —tag-groups code2cloud -parsers Terraform`

**Expected behavior**
Only the relevant trace should have been added.

**Screenshots**
https://drive.google.com/file/d/1j5FHvmiAOLJHCfgbEGXkAonw3whO_IsM/view?usp=sharing

**Desktop:**
 - OS: [macOS, Ubuntu]
 - Yor Version [0.1.178]

**Comment by ChanochShayner** [comment]
@sahilt-ti the fix PR merged, feel free to reach out in case of an issue.
