### ISSUE TITLE
Yor Doesn't Pick Up Tags When Resource Field Removed In Terraform

### ISSUE THREAD

**Issue by J-Scriv-Oblak** [bridgecrewio/yor#377]
**Describe the bug**
Yor will not pick up that a resource was updated if you remove one of its fields.

**To Reproduce**

1) Establish a resource in your terraform file.  When you run yor, it will detect the resource and apply the yor tags.
```
resource "aws_iam_user" "supercooluser" {
  name = "SuperCoolTesting"
  path = "/verycoolpath/"
}

resource "aws_s3_bucket" "demo3_test_bucket" {
  bucket        = "demo3_test_bucket"
  acl           = "private"
  force_destroy = true
}
```
2) Edit that resource to remove one of the optional attributes.  In the example above, you can remove the path attribute for the aws_iam_user resource and the force_destroy attribute for the aws_s3_bucket resource
```
resource "aws_iam_user" "supercooluser" {
  name = "SuperCoolTesting"
  tags = {...}
}

resource "aws_s3_bucket" "demo3_test_bucket" {
  bucket        = "demo3_test_bucket"
  acl           = "private"
  tags        = {...}
}
```

**Expected behavior**
The expected behavior is that your would change the git_commit_id since the resource has been changed.  It does not though

**Screenshots**
<img width="279" alt="Screen Shot 2023-05-30 at 12 12 47 PM" src="https://github.com/bridgecrewio/yor/assets/133247497/ca602ed4-0924-4557-ac76-9ca68a623f29">

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.0 LTS
 - Yor Version: v0.1.178

**Comment by nimrodkor** [comment]
This is an interesting one. Yor bases itself on running git blame, and for something that disappears... Yes I see the issue. 
We basically iterate over the **existing lines** and set the history for them, instead of looking at the resource lines / running through the history of the file. I'm open to ideas and a contribution here!

The relevant function:
https://github.com/bridgecrewio/yor/blob/main/src/common/gitservice/blame.go#L22

**Comment by srivastavaabhinav** [comment]
@nimrodkor any idea what would be the fix for the above issue? We are experiencing the similar problem. What logic should be used here to record the resource-level changes (deleted lines)?

**Comment by J-Scriv-Oblak** [comment]
Commenting to keep this open as its still an issue.  I see there is a PR open for it! https://github.com/bridgecrewio/yor/pull/409

**Comment by ChanochShayner** [comment]
@J-Scriv-Oblak I've just merged the fix PR, please let me know in case of an issue.
