### ISSUE TITLE
Factor in provider version tag compatibility

### ISSUE THREAD

**Issue by ebarti** [bridgecrewio/yor#431]
**Is your feature request related to a problem? Please describe.**
We face issues with your when using somewhat-old AWS providers. Certain resources do not accept tags in old version (eg. [aws_glue_catalog_database at 3.69](https://registry.terraform.io/providers/hashicorp/aws/3.69.0/docs/resources/glue_catalog_database)), but yor tries to add them anyway.

**Describe the solution you'd like**
Yor should verify tag compatibility per resource and provider version.

**Describe alternatives you've considered**
We currently are forced to upgrade provider versions for compatibility.

**Additional context**
N/A

**Comment by ChanochShayner** [comment]
Hey @ebarti :)

You can use flags to skip the problematic resources - 
`--skip-resource-types` to skip specific types, or `--skip-resources` to skip resources by name.

**Comment by ebarti** [comment]
I am willing to contribute this as a feature if you think it would be worth implementing. IMO it would make the tool more seamless, but I have not thought about how complex it might be to implement (especially if providers iterate through the various Hashicorp provider SDKs)

**Comment by ChanochShayner** [comment]
It will be a nice contribution!
We have the function `isBlockTaggable` here - https://github.com/bridgecrewio/yor/blob/3e30ff383f4bde7b818626da5c77f0372ba1675e/src/terraform/structure/terraform_parser.go#L661
