### ISSUE TITLE
Showstopper due to `aws_launch_template` tags triggering rebuilds

### ISSUE THREAD

**Issue by nikolay** [bridgecrewio/yor#489]
I am using [the most popular AWS EKS module](https://github.com/terraform-aws-modules/terraform-aws-eks) and just started using `yor`, but it turned to be a showstopper as it indirectly changes the tags of `aws_launch_template`, which leads to the rebuilding of the node groups every single time.

What is the recommended solution to avoid tags to resources, which source code you don't control?

Also, how can the tags be removed as I have a lot of instances?

**Comment by nikolay** [comment]
I added `--skip-resources`, but it seems that it's not working properly, as it still adds tags to skipped resources.

**Comment by ChanochShayner** [comment]
Hey @nikolay :)
You can use the `--skip-resources` flag, an example in the readme.

**Comment by nikolay** [comment]
@ChanochShayner Well, honestly, the documentation is pretty light. As I found it, it doesn't really say, for example, that these are names, not fully qualified names with the resource type, that the names are comma-delimited, etc. Also, there are parameters in the CLI. If I want to have one place for the CLI and the GitHub Actions for these ignores, I need to keep both places in sync. Please allow annotations (via comments, for example) to skip tagging or skip modules by source.
