### ISSUE TITLE
Skip Comment Feature

### ISSUE THREAD

**Issue by chanaMovshowich** [bridgecrewio/yor#531]
Problem description:
In large projects, managing tags for infrastructure resources can be time-consuming and complex.
Manually specifying which resources to skip tagging presents process challenges and complexities, often leading to errors and distortions.

Solution description:
The feature allows for adding special comments above resources that users wish to exclude from tagging, enabling skipping tagging for specific resources. 
It addresses the difficulties encountered in tagging resources within large and intricate projects, streamlining the process and reducing potential errors.

#505 
#489 
#299

**Comment by ChanochShayner** [comment]
@tsmithv11 FYI
