### ISSUE TITLE
How to persist changes when running Yor in docker container

### ISSUE THREAD

**Issue by dishikang123** [bridgecrewio/yor#550]
I am testing Yor by running it in a docker container as part of a Jenkins pipeline.  The pipeline clones the repository from GitHub and Yor was able to successfully add the tags.  Question is how would I persist the changes back to the repository?

**Comment by kwame-mintah** [comment]
@dishikang123, need a bit of clarification.

If you're using docker to run `yor`, I am assuming you're cloning the source code into the container and then running `yor` within the container? Is it possible to commit the changes and push after completion.

Alternatively, if you just want to run `yor` and not commit - but want to keep the files, you would have to do a [`docker cp`](https://docs.docker.com/reference/cli/docker/container/cp/) and save it within the working directory.

**Comment by dishikang123** [comment]
Hi,
Yes, I have tried committing the changes and was unsuccessful due to how my
ci/cd pipeline is setup. I think the concept make sense but not practical
as other deployment options.
